# .github/workflows/linux-build.yml
name: Linux Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          build-essential pkg-config git \
          libfreetype6-dev libgumbo-dev libharfbuzz-dev \
          libjbig2dec0-dev libjpeg-dev libopenjp2-7-dev \
          libglvnd-dev zlib1g-dev libmupdf-dev

    - name: Install Qt 5.15
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'linux'
        target: 'desktop'

    - name: Apply MuPDF patch & config tweaks
      run: |
        patch --forward --strip=1 < mupdf-1.23.0.patch
        sed -i 's/-lmupdf-threads/-lfreetype -lgumbo -ljbig2dec -lopenjp2 -ljpeg/' pdf_viewer_build_config.pro
        sed -i 's/-lmupdf-third//'                                     pdf_viewer_build_config.pro
        sed -i '/#define LINUX_STANDARD_PATHS/s/^\/\/\s*//' pdf_viewer/main.cpp

    - name: Compile
      env:
        MAKE_PARALLEL: ${{ vars.MAKE_PARALLEL || '$(nproc)' }}
      run: |
        ./build_linux.sh

    - name: Package artifact
      run: |
        mkdir -p dist
        cp build/sioyek dist/
    - uses: actions/upload-artifact@v4
      with:
        name: sioyek-linux-bin
        path: dist/sioyek

